gtnh.settings.blowdryerTag = 0.2.0
modName = HBM Compat
modId = hbmcompat
modGroup = io.github.hbmcompat
useModGroupForPublishing = true
autoUpdateBuildScript = false
gtnh.modules.gitVersion = false
minecraftVersion = 1.7.10
forgeVersion = 10.13.4.1614
channel = stable
mappingsVersion = 12
remoteMappings = https\://raw.githubusercontent.com/MinecraftForge/FML/1.7.10/conf/
developmentEnvironmentUserName = Developer
enableModernJavaSyntax = false
enableGenericInjection = true
generateGradleTokenClass = io.github.hbmcompat.Tags
gradleTokenVersion = VERSION
replaceGradleTokenInFile =
apiPackage =
accessTransformersFile =
usesMixins = false
separateMixinSourceSet =
usesMixinDebug = false
mixinPlugin =
mixinsPackage =
coreModClass =
containsMixinsAndOrCoreModOnly = false
forceEnableMixins = false
usesShadowedDependencies = false
minimizeShadowedDependencies = true
relocateShadowedDependencies = true
includeWellKnownRepositories = true
excludeWellKnownRepositories =
usesMavenPublishing = false
customArchiveBaseName = HBM-Compat
disableSpotless = true
disableCheckstyle = true

org.gradle.parallel = true
org.gradle.caching = true
